### PR TITLE
Update InvokeAI to v2.3.5.post2

### PR DESCRIPTION
**Pull request by qwbarch**
This works fine for me so far, but only when I have a ``invokeai`` folder pre-generated from before.
Unlike the previous version of InvokeAI used in this flake, it doesn't seem to run the configure script for you on startup when it's missing.

Their README states to run ``invokeai-configure`` as part of the initial configuration. How can I make the flake automatically run this command when the ``invokeai`` folder is missing?

### CODE REVIEW

**Comment by MatthewCroughan** [comment]
> How can I make the flake automatically run this command when the invokeai folder is missing?

You would want to add it to the wrapper script that also sets `LD_LIBRARY_PATH`  when it detects it's running in the WSL

**Comment by qwbarch** [comment]
I'm definitely misunderstanding how this works. Nix appears to infinitely try to run ``invokeai-configure`` where I've placed it, with it always instantly failing.

Here's what I've tried:
```nix
  makeWrapperArgs = [
    '' --run '
      echo "test test"
      invokeai-configure
      if [ -d "/usr/lib/wsl/lib" ]
      then
          echo "Running via WSL (Windows Subsystem for Linux), setting LD_LIBRARY_PATH=/usr/lib/wsl/lib"
          set -x
          export LD_LIBRARY_PATH="/usr/lib/wsl/lib"
          set +x
      fi
      '
    ''
  ] # The rest of this is omitted to keep the example small
```
This results in the script spamming ``test test`` until I eventually ``ctrl+c`` to force close.

I thought this could be due to ``invokeai-configure`` not being on the PATH due to nix shenanigans, but it appears to actually be called.

Any idea on why this interaction is happening? Sorry for the dumb questions, I'm getting stuck on something that should be trivial

**Comment by MatthewCroughan** [comment]
You didn't specify an if statement, so if it runs itself again, it will run infinitely.

**Comment by fnordpig** [comment]
Hi!  Is there anything blocking this?  Unrelated question: How did you run the pynixify script to generate the changes in the dependencies?  I'll be happy to make any changes necessary to get this promoted though.  I'd also like to rev up KoboldAI and switch to this fork, which seems to be the active one: https://github.com/henk717/KoboldAI

**Comment by qwbarch** [comment]
> Hi! Is there anything blocking this? Unrelated question: How did you run the pynixify script to generate the changes in the dependencies? I'll be happy to make any changes necessary to get this promoted though. I'd also like to rev up KoboldAI and switch to this fork, which seems to be the active one: https://github.com/henk717/KoboldAI

I actually have no idea how to use pynixify, all of the changes I made were done manually.
IIRC was stuck at getting it to not infinitely loop, and adding a check for if the ``invokeai`` directory existed wasn't enough to stop it from looping.
I'll try looking into this again tomorrow and see if I can get this PR finished

**Comment by qwbarch** [comment]
@MatthewCroughan Do you mind taking a look at my current commit?

If I put an ``echo "Hello world!"`` inside the if statement, it halts as expected.
With the ``invokeai-configure`` call, it still infinitely loops. I don't understand this enough to know why this happens unfortunately.
Am I making a really newbie nix mistake here? Sorry if this is supposed to be really simple to figure out, I'm somehow still stumped on this issue.

My guess would have to be that ``invokeai-configure`` acts as a tui when you run it, instead of the usual stdout. Maybe that has to do with it infinitely looping?

**Comment by qwbarch** [comment]
Ah just realized I have nixfmt on, causing some formatting noise, which I'll cleanup later. This is the main thing to see:
```
--run '
         if [ ! -d "${builtins.getEnv "HOME"}/invokeai" ]
         then
           echo "Running invokeai-configure"
           set -x
           invokeai-configure
           set +x
         fi
         '
```

**Comment by MatthewCroughan** [comment]
@qwbarch `builtins.getEnv` won't work in a flake. You're going to have to look the variable up in Bash at runtime like `$HOME`.

**Comment by qwbarch** [comment]
@MatthewCroughan Thanks for pointing me towards the right direction. Could you take a look at the changes when you have time? The PR should be good to go.

**Comment by qwbarch** [comment]
Sorry I removed something while cleaning up the formatting noise and ended up breaking it. Trying to find out the issue right now

**Comment by MatthewCroughan** [comment]
@qwbarch the runtime directory that invokeai chooses could be different than `~/invokeai` right? In this case, how does it look it up? Instead of `$HOME` we should be computing the full path to wherever invokeai wants to put its state, `$HOME` is just the default, but perhaps we can be a bit smarter about this. I suspect it probably uses an environment variable too.

**Comment by qwbarch** [comment]
I couldn't find anything on environmental variables, but ``invokeai`` does allow the user to choose the runtime directory via the ``--root_dir`` argument.

Is there a way for me to read what arguments are passed after the ``--`` for ``nix run``?
```nix
nix run .#invokeai-nvidia -- --web --root_dir=my_custom_dir
```

**Comment by fnordpig** [comment]
@MatthewCroughan thanks for the assists on the PR I'm learning a lot about Nix. Is there anything that shows how to generate the package files with pynixify rather than manually writing them?  I was planning to do the kobold ai rev but the new fork has a lot of new and different deps. Sorry for the newb question.

**Comment by MatthewCroughan** [comment]
@fnordpig I've been playing with the idea of upstreaming these overlays into nixpkgs, anything you need to package should be upstreamed into Nixpkgs first, and only cherry-picked into our repo if it's taking way too long to merge. It's too much of a maintenance burden to keep hold of these overlays, and it's more valuable if they're put into Nixpkgs instead.

**Comment by fnordpig** [comment]
> upstreaming these overlays into nixpkgs, anything you need to package should be upstreamed into Nixpkgs first, and only cherry-picked into our repo if it's taking way too long to merge.

Ok that seems reasonable. But I assume pynixify is a step there. I'll spend some time this week learning the mechanics. But my nixnoob guess is:

* get repo for the projects supported and their releases supported

* run pynixify in such a way you get the right nixpkgs format

* learn how to submit to nixpkgs and go through that process 

* once everything is merged into the general nixpkgs repo and disruption this project builds using standard nixpkgs

I'll dig into learning how to do these things. It seems like the globally better way to do it even if it's a little slower perhaps end to end as everyone using the packages benefits.

**Comment by MatthewCroughan** [comment]
> even if it's a little slower perhaps end to end as everyone using the packages benefits.

I've realised by trying to maintain this repo that waiting for things to get merged into Nixpkgs creates less work than holding the overlays ourselves and trying to update them over time. Net maintenance is reduced by putting stuff into Nixpkgs, whilst also increasing the value of Nixpkgs.

**Comment by qwbarch** [comment]
> I couldn't find anything on environmental variables, but `invokeai` does allow the user to choose the runtime directory via the `--root_dir` argument.
> 
> Is there a way for me to read what arguments are passed after the `--` for `nix run` within `makeWrapperArgs`?
> 
> ```
> nix run .#invokeai-nvidia -- --web --root_dir=my_custom_dir
> ```

@MatthewCroughan Thoughts on what to do for this? Since a user can pass the ``--root_dir`` arg, the only thing I can think of is to parse the command arguments and then pass that to ``invokeai-configure``

**Comment by pmarreck** [comment]
Hey @MatthewCroughan I've been following this project for a while, just wanted to say thanks (and that I'd also appreciate an invokeai version bump), but also that this project is quite a great soft-selling point for Nix in general, since I usually find it impossible to run multiple Python AI projects outside Docker instances (both due to Nix's architecture and Python's conflicting assumptions, as well as Python's bad dependency management in a multitenant situation- a problem that I've also seen outside Nix with other Linux distros), but this will get the whole thing up with just 1 command, which as a usable demo is just _fantastic_. If you're a Nix advocate like me, then figuring out how to maintain this (and riding the wave of interest in running huggingface models locally more generally, such as the recently released Mistral-7B) will go a long way towards that IMHO.

At this point I would normally offer my help, but unfortunately I have a 2 year old and a new job and that leaves almost no free time these days, so my moral support will have to suffice for now =)

**Pull request closed without merging**
