### PR TITLE
add text-generation-webui (textgen) to the flake

### PR DESCRIPTION
**Pull request by jpetrucciani**
This is a bit messy, but it does get the basics of [text-generation-webui (textgen)](https://github.com/oobabooga/text-generation-webui) running from within this flake! I'm still working on ensuring that every feature works as expected, but for now, the basics are working for nvidia (testing with an RTX 3090), within WSL2! I do not have an AMD based machine to test with at the moment, outside of some NUCs that have integrated AMD gpus (I'm assuming that won't work as one might suspect)

### CODE REVIEW

**Comment by max-privatevoid** [comment]
Thanks for the contribution!

Unfortunately, this doesn't seem to work on my test machine which I've used for test driving the other projects in this repo so far (NVIDIA GTX 1070Ti and AMD Radeon RX 5500 XT installed simultaneously). It spits out a massive error (`textgen-nvidia`):
```
Gradio HTTP request redirected to localhost :)
bin /nix/store/wcpicrxalgf863lp8n16rv8qnnddmsj8-python3.10-bitsandbytes-0.38.0/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /nix/store/ccm7316rqdmffrg2zlzxd4smh19xjy07-pipewire-0.3.68-jack/lib did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/1147829,unix/TITAN'), PosixPath('local/TITAN')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/max/.nix-profile/etc/xdg'), PosixPath('/nix/var/nix/profiles/default/etc/xdg'), PosixPath('/etc/xdg')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/nix/var/nix/profiles/default/share/pixmaps'), PosixPath('/nix/var/nix/profiles/default/share/icons'), PosixPath('/home/max/.icons')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/max /home/max/.nix-profile')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('repl=/etc/nix/flake-channels/system/repl.nix'), PosixPath('home-manager=/etc/nix/flake-channels/home-manager'), PosixPath('nixpkgs=/etc/nix/flake-channels/nixpkgs')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/nix/nixpkgs-config.nix')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/nix/var/nix/profiles/default/share/info'), PosixPath('/run/current-system/sw/info'), PosixPath('/home/max/.nix-profile/share/info'), PosixPath('/home/max/.nix-profile/info'), PosixPath('/etc/profiles/per-user/max/info'), PosixPath('/nix/var/nix/profiles/default/info')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/nix/var/nix/profiles/default/lib/gtk-4.0'), PosixPath('/home/max/.nix-profile/lib/gtk-3.0'), PosixPath('/nix/var/nix/profiles/default/lib/gtk-3.0'), PosixPath('/home/max/.nix-profile/lib/gtk-2.0'), PosixPath('/nix/var/nix/profiles/default/lib/gtk-2.0'), PosixPath('/home/max/.nix-profile/lib/gtk-4.0')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/profiles/per-user/max/lib/mozilla/plugins'), PosixPath('/run/current-system/sw/lib/mozilla/plugins'), PosixPath('/home/max/.nix-profile/lib/mozilla/plugins'), PosixPath('/nix/var/nix/profiles/default/lib/mozilla/plugins')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('-config /nix/store/aipygjqhrl53197bpvamnvw80i2vm677-xserver.conf -xkbdir /nix/store/18kg67dfchk2l7ni9i0hrpbdspbxlrzw-xkeyboard-config-2.33/etc/X11/xkb -logfile /dev/null -nolisten tcp')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/run/current-system/sw/lib/qt-6/qml'), PosixPath('/etc/profiles/per-user/max/lib/qt-5.15.8/qml'), PosixPath('/nix/var/nix/profiles/default/lib/qt-6/qml'), PosixPath('/home/max/.nix-profile/lib/qt-5.15.8/qml'), PosixPath('/nix/var/nix/profiles/default/lib/qt-5.15.8/qml'), PosixPath('/etc/profiles/per-user/max/lib/qt-6/qml'), PosixPath('/home/max/.nix-profile/lib/qt-6/qml')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/nix/var/nix/profiles/default/share/terminfo'), PosixPath('/home/max/.nix-profile/share/terminfo')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/nix/var/nix/profiles/default')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/nix/var/nix/profiles/default/lib/libexec'), PosixPath('/etc/profiles/per-user/max/lib/libexec'), PosixPath('/run/current-system/sw/lib/libexec'), PosixPath('/home/max/.nix-profile/lib/libexec')}
  warn(msg)
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/run/current-system/sw/lib/qt4/plugins'), PosixPath('/home/max/.nix-profile/lib/qt-6/plugins'), PosixPath('/home/max/.nix-profile/lib/qt4/plugins'), PosixPath('/etc/profiles/per-user/max/lib/qt-5.15.8/plugins'), PosixPath('/nix/var/nix/profiles/default/lib/qt-5.15.8/plugins'), PosixPath('/etc/profiles/per-user/max/lib/kde4/plugins'), PosixPath('/etc/profiles/per-user/max/lib/qt-6/plugins'), PosixPath('/nix/var/nix/profiles/default/lib/kde4/plugins'), PosixPath('/run/current-system/sw/lib/qt-6/plugins'), PosixPath('/nix/var/nix/profiles/default/lib/qt4/plugins'), PosixPath('/nix/var/nix/profiles/default/lib/qt-6/plugins'), PosixPath('/etc/profiles/per-user/max/lib/qt4/plugins'), PosixPath('/home/max/.nix-profile/lib/kde4/plugins'), PosixPath('/home/max/.nix-profile/lib/qt-5.15.8/plugins'), PosixPath('/run/current-system/sw/lib/kde4/plugins')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/nix/store/3avk9g7kp6k2ykigsmw36kfpsic6qpy9-cuda-native-redist-11.7/lib/libcudart.so.11.0'), PosixPath('/nix/store/3avk9g7kp6k2ykigsmw36kfpsic6qpy9-cuda-native-redist-11.7/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: /nix/store/3avk9g7kp6k2ykigsmw36kfpsic6qpy9-cuda-native-redist-11.7/lib/libcudart.so.11.0
/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Setup Failed!
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "/nix/store/ndd2pfikj6cjmrvhyjff7cmxzcp88jg4-textgen-patchedSrc/server.py", line 44, in <module>
    from modules import chat, shared, training, ui
  File "/nix/store/ndd2pfikj6cjmrvhyjff7cmxzcp88jg4-textgen-patchedSrc/modules/training.py", line 13, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/peft/peft_model.py", line 31, in <module>
    from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/peft/tuners/__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/peft/tuners/lora.py", line 36, in <module>
    import bitsandbytes as bnb
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/nix/store/60sxhyszxixh2v17gc6k0dndh5yvhr71-python3-3.10.10-env/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```
We should find a way to bundle the CUDA libraries correctly, assuming that's possible without locking ourselves to one particular GPU driver version, as well as a way to shut up `bitsandbytes` by limiting its view on environment variables.

Curiously, the `textgen-amd` variant also goes looking for CUDA libraries and fails in the same manner, expect with the `bitsandbytes` library coming from `/nix/store/psmrdjhfbdm3zgqqzi80ar7vzijsa72c-python3.10-bitsandbytes-0.38.0`.

I'm also worried about this: The second time you run the project, it prints this at the beginning:
```
cp: cannot create regular file '/home/max/.textgen/state/prompts/./Alpaca.txt': Permission denied
cp: cannot create regular file '/home/max/.textgen/state/prompts/./Alpaca-with-Input.txt': Permission denied
cp: cannot create regular file '/home/max/.textgen/state/prompts/./GPT-4chan.txt': Permission denied
cp: cannot create regular file '/home/max/.textgen/state/prompts/./Open Assistant.txt': Permission denied
cp: cannot create regular file '/home/max/.textgen/state/prompts/./QA.txt': Permission denied
```
It appears the stateDir you create isn't properly writable.

**Comment by jpetrucciani** [comment]
@max-privatevoid Thanks for testing this out! Definitely some work left to be done here. I've just started a new job this week so I may get back to looking at this in the upcoming weekend, or next week!

**Comment by luxus** [comment]
looks like the job takes more time then expected.
will you sill have time @jpetrucciani ?

**Comment by MatthewCroughan** [comment]
@jpetrucciani I don't think this is too hard to fix, but it's about time, energy, money and commitment. Which is why I've started the sponsorship. Getting this working is one of the $200 goals, along with documentation.

**Comment by jpetrucciani** [comment]
Playing with this more - I'm not sure that `bitsandbytes` will be very cooperative in the long run. It is also only required for very specific cases/models - I think that for now, we might want to just avoid trying to add it. That should allow most CUDA(/ROCM potentially) setups to work.

> It appears the stateDir you create isn't properly writable.

Actually, I think that it's because the files copied out were originally `444`, so it fails in attempting to write over top of them the next time you boot it - I've fixed that in the new commit.

> looks like the job takes more time then expected.

Yep, still working on getting acquainted/settled at the new place. I will be working more on this if/as I have free time.

> I don't think this is too hard to fix, but it's about time, energy, money and commitment.

For sure - I definitely don't want you to feel like you have to fix this for me though

**Comment by MatthewCroughan** [comment]
@jpetrucciani I actually meant to ping @luxus not you, sorry about that! I don't feel any particular way about it, I just want to get started on funding the project. Luxus donated earlier, and I felt I owed a response to his query :)

**Comment by MatthewCroughan** [comment]
I've been hacking on this a bit. In order to fix the bitsandbytes loading issue, you need to set `LD_LIBRARY_PATH=/run/opengl-driver/lib` on NixOS.

Once this is done, gptq models still can't be loaded because of `ModuleNotFoundError: No module named ‘llama_inference_offload’`. So the solution to that is to launch the server with `--autogptq`, which meant I had to package this https://github.com/PanQiWei/AutoGPTQ

Thirdly, once this is done, gptq models can be loaded successfully, but when trying to compute a result with them, you'll get a CUDA runtime error like this:

```
Traceback (most recent call last):
  File "/nix/store/b45sf96075m4nwi7v49ry8z4yjnzypgn-textgen-patchedSrc/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/nix/store/b45sf96075m4nwi7v49ry8z4yjnzypgn-textgen-patchedSrc/modules/text_generation.py", line 274, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/nix/store/ppnkh9zi08sfyg24jmw2964y0k4r1znj-python3-3.10.11-env/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 390, in generate
    return self.model.generate(**kwargs)
  File "/nix/store/ppnkh9zi08sfyg24jmw2964y0k4r1znj-python3-3.10.11-env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/nix/store/ppnkh9zi08sfyg24jmw2964y0k4r1znj-python3-3.10.11-env/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/nix/store/ppnkh9zi08sfyg24jmw2964y0k4r1znj-python3-3.10.11-env/lib/python3.10/site-packages/transformers/generation/utils.py", line 2579, in sample
    next_tokens.tile(eos_token_id_tensor.shape[0], 1).ne(eos_token_id_tensor.unsqueeze(1)).prod(dim=0)
RuntimeError: 
  #ifdef __HIPCC__
  #define ERROR_UNSUPPORTED_CAST ;
  // corresponds to aten/src/ATen/native/cuda/thread_constants.h
  #define CUDA_OR_ROCM_NUM_THREADS 256
  // corresponds to aten/src/ATen/cuda/detail/OffsetCalculator.cuh
  #define MAX_DIMS 16
  #ifndef __forceinline__
```

It continues for a while, then results in a more readable error message:

```
nvrtc: error: failed to open libnvrtc-builtins.so.11.7.
  Make sure that libnvrtc-builtins.so.11.7 is installed correctly.
Output generated in 3.40 seconds (0.00 tokens/s, 0 tokens, context 16, seed 1251234274)
```

**Comment by MatthewCroughan** [comment]
I was successfully able to load a model and run it with CUDA via bitsandbytes as long as I set `export LD_LIBRARY_PATH=/run/opengl-driver/lib:${cudaPackages.cudatoolkit}/lib` in our wrapper.

**Comment by MatthewCroughan** [comment]
All working now, I even got characters working. Though I think this business of patching the directories referred to in the source code is not sustainable, we have to come up with a better way!

You can try it out like `nix run github:nixified-ai/flake/mc/wip-text-generation-webui#textgen-nvidia -- --autogptq` and adding the https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GPTQ model to `~/.textgen/state/models`

image

**Comment by mitchmindtree** [comment]
Nice one @jpetrucciani, @MatthewCroughan!

If one were to this branch and have a go at adding an `-amd` variant, where should they look to start? Is there a `rocmPackages` equivalent to `cudaPackages`?

**Comment by MatthewCroughan** [comment]
@mitchmindtree more or less, yes, just look at how invokeai is implemented here in this repo.

**Comment by mitchmindtree** [comment]
Ahh It looks like for the most part the `textgen-amd` package is already setup similarly to the `invokeai-amd` package at a high level, however it seems there are some issues with the `bitsandbytes` python dep.

When doing a `nix build .#textgen-amd`, we get some errors in `bitsandbytes` about `cudaPackages` not existing - I'm guessing it'll need some patching for rocm support.

**Comment by MatthewCroughan** [comment]
bitsandbytes is a problematic dependency, yes. Try basing your work on my `mc/wip-text-generation-webui` branch though, the reason for your error is because we are using torchvision-bin, rather than torchWithCuda/torchWithRocm from nixpkgs, which means they don't have an instance of `cudaPackages` as a method/attr inside of them.

**Pull request closed without merging**
