### PR TITLE
NixOS modules

### PR DESCRIPTION
**Pull request by max-privatevoid**
- InvokeAI
  - [x] NVIDIA
  - [x] AMD
- KoboldAI
  - [x] NVIDIA
  - [x] AMD

### CODE REVIEW

**Comment by max-privatevoid** [comment]
Has some problems on AMD right now. Infinitely stuck in "Preparing".

**Comment by max-privatevoid** [comment]
Turns out "infinite" was just a different way of saying "longer than I was willing to wait". This is what's known as a ROCm Moment.

**Comment by MatthewCroughan** [comment]
I've tested this as working in WSL on an NVidia GPU

**Comment by MatthewCroughan** [comment]
TODO: would be good to add some CPU Only automated nixosTests

**Pull request merged**
